import { CONFIG, type ExperienceState } from '../config/experienceConfig'; import { clamp, smoothstep } from '../utils/math';
import { loadLecture, type Lecture } from '../content'; import { AudioSystem } from './AudioSystem'; import { WaterSystem } from './WaterSystem'; import { TextSystem } from './TextSystem'; import { RopeController } from './RopeController';

export class ExperienceController {
  private state:ExperienceState='IDLE'; private lecture?:Lecture; private startTime=0; private lastTime=0; private segment=0; private flushStart=-1; private switching=false; private water:WaterSystem; private texts:TextSystem; private audio=new AudioSystem();
  private bubble=this.q<HTMLElement>('#speech'); private teacher=this.q<HTMLImageElement>('#teacher'); private caption=this.q<HTMLElement>('#caption'); private status=this.q<HTMLElement>('#status');
  constructor(){this.water=new WaterSystem(this.q('#water'));this.texts=new TextSystem(this.q('#text-layer'));new RopeController(this.q('#rope'),()=>this.flush());this.q('#start').addEventListener('pointerup',()=>void this.start());}
  private q<T extends Element>(s:string){return document.querySelector<T>(s)!;}
  async ready(){this.lecture=await loadLecture();this.caption.textContent=`${this.lecture.entry.subject}・${this.lecture.entry.title}`;requestAnimationFrame(t=>this.frame(t));}
  private async start(){if(!this.lecture||this.state!=='IDLE')return;this.state='LECTURE';this.q('#start').classList.add('hidden');this.startTime=performance.now();this.lastTime=this.startTime;await this.audio.start(this.lecture.raw,this.lecture.entry.audio,()=>void this.continueLecture());}
  private frame(ms:number){const dt=Math.min(.04,(ms-this.lastTime)/1000||0);this.lastTime=ms;const t=ms/1000;let progress=0,flush=0;if(this.state!=='IDLE'&&this.state!=='SILENCE'){progress=clamp((ms-this.startTime)/(CONFIG.lectureDuration*1000));if(this.state==='FLUSHING'&&this.flushStart>=0)flush=clamp((ms-this.flushStart)/(CONFIG.flush.duration*1000));}
    if(this.state!=='IDLE'&&this.state!=='FLUSHING'&&this.state!=='SILENCE')this.updateState(progress);this.water.update(progress,t,flush);const immersion=this.water.immersionAt(CONFIG.teacherMouthY,t);const waterAmount=clamp(1-this.water.level);const pulse=(immersion>.08&&immersion<.9)?Math.sin(t*9)*.5+.5:0;this.audio.update(immersion,pulse,waterAmount);const lectureProgress=clamp(this.audio.currentTime/this.audio.duration);this.updateTranscript(lectureProgress);this.texts.update(dt,t,x=>this.water.surface(x,t,1+flush*2.5),flush);this.teacher.src=`${import.meta.env.BASE_URL}images/teacher${progress<.38?1:progress<.68?2:progress<.86?3:4}.png`;document.documentElement.style.setProperty('--pressure',`${smoothstep(.55,1,progress)}`);if(this.state==='FLUSHING'&&flush>=1)this.silence();requestAnimationFrame(n=>this.frame(n));}
  private updateState(p:number){this.state=p<.2?'LECTURE':p<.38?'OVERFLOW':p<.82?'FLOODING':'SUBMERGED';this.status.textContent=this.state==='LECTURE'?'老師正在講課':this.state==='OVERFLOW'?'內容開始裝不下':this.state==='FLOODING'?'資訊持續累積':'老師仍然在講';}
  private updateTranscript(progress:number){if(!this.lecture||this.state==='IDLE'||this.state==='SILENCE'||this.state==='FLUSHING')return;const multiplier=1+smoothstep(.3,.95,progress)*1.35;const totalChars=this.lecture.sentences.reduce((sum,s)=>sum+s.length,0);const spokenBudget=Math.max(1,totalChars*progress*multiplier);let cumulative=0;let expected=0;for(const sentence of this.lecture.sentences){if(cumulative>spokenBudget)break;expected++;cumulative+=sentence.length;}expected=Math.min(this.lecture.sentences.length,expected);while(this.segment<expected){const s=this.lecture.sentences[this.segment++];const span=document.createElement('span');span.textContent=s+' ';this.bubble.append(span);if(this.bubble.scrollHeight>this.bubble.clientHeight||progress>.34){this.texts.spawn(s,1+progress);while(this.bubble.scrollHeight>this.bubble.clientHeight&&this.bubble.childElementCount>1)this.bubble.firstElementChild?.remove();if(progress>.55&&this.bubble.childElementCount>3)this.bubble.firstElementChild?.remove();}}}
  private flush(){if(this.state==='IDLE'||this.state==='FLUSHING'||this.state==='SILENCE')return;this.state='FLUSHING';this.flushStart=-1;this.status.textContent='';setTimeout(()=>{this.flushStart=performance.now();this.audio.flush();document.body.classList.add('flushing');},CONFIG.flush.delay);}
  private silence(){if(this.state==='SILENCE')return;this.state='SILENCE';this.flushStart=-1;this.texts.clear();this.bubble.replaceChildren();this.teacher.src=`${import.meta.env.BASE_URL}images/teacher1.png`;this.status.textContent='';document.body.classList.remove('flushing');document.body.classList.add('silent');setTimeout(()=>void this.nextLecture(),CONFIG.silenceDuration*1000);}
  private async continueLecture(){if(this.switching||!this.lecture||this.state==='FLUSHING'||this.state==='SILENCE'||this.state==='IDLE')return;this.switching=true;const choices=this.lecture.catalog.filter(entry=>entry.id!==this.lecture!.entry.id);const next=choices[Math.floor(Math.random()*choices.length)];const lecturePromise=loadLecture(next.id);const audioPromise=this.audio.continueLecture('',next.audio,()=>void this.continueLecture());this.lecture=await lecturePromise;this.caption.textContent=`${this.lecture.entry.subject}・${this.lecture.entry.title}`;this.segment=0;await audioPromise;this.switching=false;}
  private async nextLecture(){if(!this.lecture)return;this.switching=true;const choices=this.lecture.catalog.filter(entry=>entry.id!==this.lecture!.entry.id);const next=choices[Math.floor(Math.random()*choices.length)];this.lecture=await loadLecture(next.id);this.caption.textContent=`${this.lecture.entry.subject}・${this.lecture.entry.title}`;this.segment=0;this.startTime=performance.now();this.lastTime=this.startTime;document.body.classList.remove('silent');this.state='LECTURE';this.status.textContent='老師正在講課';await this.audio.restartAfterSilence(this.lecture.raw,this.lecture.entry.audio,()=>void this.continueLecture());this.switching=false;}
}
