import { CONFIG } from '../config/experienceConfig'; import { rand } from '../utils/math';
type Fragment = { text:string;x:number;y:number;vx:number;vy:number;r:number;vr:number;scale:number;opacity:number;submerged:boolean };
export class TextSystem {
  private items: Fragment[] = []; private width=1; private height=1; private dpr=1;
  constructor(private canvas:HTMLCanvasElement){ this.resize(); addEventListener('resize',()=>this.resize()); }
  private resize(){const r=this.canvas.getBoundingClientRect();this.dpr=Math.min(devicePixelRatio,2);this.canvas.width=r.width*this.dpr;this.canvas.height=r.height*this.dpr;this.width=r.width;this.height=r.height;}
  spawn(text:string, intensity=1){if(this.items.length>=CONFIG.maxFloatingTexts)return; const pieces=text.split(/[，、：]/).filter(p=>p.length>1); for(const p of pieces.slice(0,Math.ceil(intensity*2))){if(this.items.length>=CONFIG.maxFloatingTexts)break;this.items.push({text:p.slice(0,20),x:rand(.43,.69)*this.width,y:rand(.185,.22)*this.height,vx:rand(-24,24),vy:rand(-72,-38),r:rand(-.16,.16),vr:rand(-.34,.34),scale:rand(.75,1.08),opacity:rand(.62,.9),submerged:false});}}
  update(dt:number,time:number,surface:(x:number)=>number,flush:number){const ctx=this.canvas.getContext('2d')!;ctx.setTransform(this.dpr,0,0,this.dpr,0,0);ctx.clearRect(0,0,this.width,this.height);const dx=CONFIG.flush.drainX*this.width,dy=CONFIG.flush.drainY*this.height;for(const f of this.items){const sy=surface(f.x);if(flush>0){const ax=dx-f.x,ay=dy-f.y,d=Math.max(22,Math.hypot(ax,ay));const force=CONFIG.flush.suctionStrength*(900+flush*2600)/d;f.vx+=ax/d*force*dt;f.vy+=ay/d*force*dt+flush*120*dt;f.vr+=dt*(4+flush*12);f.scale*=Math.max(.94,1-dt*flush*1.25);f.opacity=Math.min(f.opacity,1-flush*.94);}else if(f.y>sy){f.submerged=true;f.vy+=(f.scale<.9?5:-12)*dt;f.vx+=Math.sin(time+f.y*.01)*4*dt;f.vy*=.985;}else f.vy+=26*dt;f.x+=f.vx*dt;f.y+=f.vy*dt;f.r+=f.vr*dt;if(f.y>this.height+50||Math.hypot(dx-f.x,dy-f.y)<18)f.opacity=0;ctx.save();ctx.translate(f.x,f.y);ctx.rotate(f.r);ctx.scale(f.scale,f.scale);ctx.globalAlpha=Math.max(0,f.opacity);ctx.font='500 15px "Noto Sans TC",sans-serif';ctx.fillStyle=f.submerged?'#123d59':'#182b31';ctx.fillText(f.text,0,0);ctx.restore();}this.items=this.items.filter(f=>f.opacity>0);}
  clear(){this.items=[];}
}
